services:
  redis:
    image: "redis:7.0"
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - superset-net
  celery:
    build:
      context: ./injector
      dockerfile: Dockerfile.celery
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      INJECTOR_HIGH_PRIORITY_WORKERS: ${INJECTOR_HIGH_PRIORITY_WORKERS}
      INJECTOR_MEDIUM_PRIORITY_WORKERS: ${INJECTOR_MEDIUM_PRIORITY_WORKERS}
      INJECTOR_LOW_PRIORITY_WORKERS: ${INJECTOR_LOW_PRIORITY_WORKERS}
      INJECTOR_WORKER_CONCURRENCY: ${INJECTOR_WORKER_CONCURRENCY}
      INJECTOR_DOWNLOAD_QUEUE_LIMIT: ${INJECTOR_DOWNLOAD_QUEUE_LIMIT}
    depends_on:
      - redis
      - postgres
    volumes:
      - ./injector/:/app
      - ./data:/data
    networks:
      - superset-net
  postgres:
    image: "postgres:16.3"
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:${DB_PORT}:${DB_PORT}"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: -p ${DB_PORT}
    networks:
      - superset-net

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    ports:
      - "127.0.0.1:${SUPERSET_PORT}:${SUPERSET_PORT}"
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      SUPERSET_ADMIN_USER: ${SUPERSET_ADMIN_USER}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_PORT: ${SUPERSET_PORT}
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/requirements.txt:/app/requirements.txt
      - ./superset/wait_for_it.sh:/app/wait_for_it.sh 
      - ./superset/entry_point.sh:/app/entry_point.sh 
      - ./superset/branding:/app/branding/static/branding
    depends_on:
      - postgres
    networks:
      - superset-net

  injector:
    build:
      context: ./injector
      dockerfile: Dockerfile
    container_name: injector
    volumes:
      - ./data:/data
      - ./injector:/app
    depends_on:
      - postgres
      - redis
      - celery
    networks:
      - superset-net
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: ["python", "init_harvest.py"] 

  nginx:
    image: nginx:1.27
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - superset
    networks:
      - superset-net

networks:
  superset-net:
    name: superset-net