services:
  postgres:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - superset-net

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    container_name: superset
    ports:
      - "${SUPERSET_PORT}:8088"
    environment:
      SUPERSET_CONFIG_PATH: /app/pythonpath/superset_config.py
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      SECRET_KEY: ${SECRET_KEY}
      SUPERSET_ADMIN_USER: ${SUPERSET_ADMIN_USER}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_PORT: ${SUPERSET_PORT}
    volumes:
      - ./superset/superset_config.py:/app/pythonpath/superset_config.py
      - ./superset/requirements.txt:/app/requirements.txt
      - ./superset/setup.py:/app/setup.py
      - ./superset/wait_for_it.sh:/app/wait_for_it.sh 
      - ./superset/entry_point.sh:/app/entry_point.sh 
    depends_on:
      - postgres
    networks:
      - superset-net

  injector:
    build:
      context: ./injector
      dockerfile: Dockerfile
    container_name: injector
    volumes:
      - ./data:/data
      - ./injector:/app
    depends_on:
      - postgres
    networks:
      - superset-net
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    command: ["python", "/app/inject.py"] 

networks:
  superset-net:
    name: superset-net