FROM python:3.9-slim

RUN apt-get update && apt-get install -y cron libpq-dev gcc

COPY . /app/

RUN pip install -r /app/requirements.txt

RUN chmod +x /app/entry_point_celery.sh

WORKDIR /app

ENTRYPOINT ["/app/entry_point_celery.sh"]

ENV PYTHONUNBUFFERED=1